trigger: none

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - edl-blueprint/dataprep/src/ddo_transform/*

variables:
  pythonWorkingDir: 'edl-blueprint/dataprep/src/ddo_transform'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: pip install -r requirements_dev.txt && pip install -r requirements.txt
  workingDirectory: $(pythonWorkingDir)
  displayName: 'Install requirements'

- script: make lint && make test
  workingDirectory: $(pythonWorkingDir)
  displayName: 'Run lint tests'
